#!/bin/bash
app=rssbridge

# Retrieve arguments
domain=$1
path=$2
admin=$3
is_public=$4



# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app
if [[ ! $? -eq 0 ]]; then
    exit 1
fi
# Save app settings
sudo yunohost app setting $app admin -v "$admin"
sudo yunohost app setting $app is_public -v "$is_public"

# Copy source files
echo "Downloading rssbridge master version..."
sudo apt-get install unzip
mkdir ../tmp
sudo wget -O ../tmp/master.zip "https://github.com/sebsauvage/rss-bridge/archive/master.zip"
echo "Deploying source files..."
unzip ../tmp/master.zip -d ../tmp/
sudo cp -r /tmp/rss-bridge-master/* $final_path



#sudo mkdir -p $final_path/vendor/simplehtmldom
#sudo wget --no-check-certificate 'http://sourceforge.net/projects/simplehtmldom/files/simple_html_dom.php'
#sudo cp simple_html_dom.php /var/www/$app/vendor/simplehtmldom


# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# If app is public, add url to SSOWat conf as skipped_uris
if [ "$is_public" = "Yes" ];
then
  # unprotected_uris allows SSO credentials to be passed anyway.
  sudo yunohost app setting $app unprotected_uris -v "/"
fi

# Restart services
sudo service nginx reload
sudo yunohost app ssowatconf
