#!/bin/bash
app=rssbridge

# Retrieve arguments
domain=$(sudo yunohost app setting $app domain)
path=$(sudo yunohost app setting $app path)
admin=$(sudo yunohost app setting $app admin)
is_public=$(sudo yunohost app setting $app is_public)

# Remove trailing "/" for next commands
path=${path%/}


# Copy source files
final_path=/var/www/$app
sudo mkdir -p $final_path
sudo apt-get install unzip
sudo wget 'https://github.com/sebsauvage/rss-bridge/archive/master.zip'
unzip master.zip
sudo cp -r rss-bridge-master/* $final_path
#sudo mkdir -p $final_path/vendor/simplehtmldom
#sudo wget --no-check-certificate 'http://sourceforge.net/projects/simplehtmldom/files/simple_html_dom.php'
#sudo cp simple_html_dom.php /var/www/$app/vendor/simplehtmldom

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# If app is public, add url to SSOWat conf as skipped_uris
if [ "$is_public" = "Yes" ];
then
  # See install script
  sudo yunohost app setting $app unprotected_uris -v "/"
  # Remove old settings
  sudo yunohost app setting $app skipped_uris -d
fi

# Restart services
sudo service nginx reload
sudo yunohost app ssowatconf

